networks:
  reverse-proxy:
    external: true
  edge:
    external: true

services:
  traefik:
    image: traefik:v3.5
    restart: unless-stopped
    command:
      - --providers.file.directory=/etc/traefik/dynamic
      - --providers.file.watch=true
      - --entrypoints.web.address=:80
      - --entrypoints.websecure.address=:443
      - --log.level=INFO
    ports:
      - "80:80"
      - "443:443"
    environment:
      - BASE_DOMAIN=${BASE_DOMAIN}
    volumes:
      - ./templates:/etc/traefik/dynamic:row
    networks: [edge]

  caddy-infra:
    build: .
    environment:
      BASE_DOMAIN: ${BASE_DOMAIN}
      CLOUDFLARE_API_TOKEN: ${CLOUDFLARE_API_TOKEN}
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile:ro
      - caddy_infra_data:/data
      - caddy_infra_config:/config
    networks:
      reverse-proxy:
        ipv4_address: 10.0.69.2
      edge: {}
    depends_on:
      - traefik

volumes:
  caddy_infra_data: {}
  caddy_infra_config: {}
